version: "3.7"
services:
    # image project
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on:
            - redis
        networks:
            - laravel-eti

    # nginx
    nginx:
        image: 'nginx:stable-alpine'
        ports:
            - "8989:80"
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
            - ./:/var/www
        networks:
            - laravel-eti

    # mariadb
    mariadb:
        image: mariadb:10.2
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes:
            - ${PWD}/mariadb:/var/lib/mysql
        ports:
            - 3388:3306
        networks:
            - laravel-eti

    # queue
    queue:
        build:
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes:
            - ./:/var/www
        depends_on:
            - redis
            - app
        networks:
            - laravel-eti

    # redis
    redis:
        image: redis:latest
        networks:
            - laravel-eti

networks:
    laravel-eti:
        driver: bridge
